"""Add apple_id to apps

Revision ID: 2355c6e79800
Revises: 45ca633d638a
Create Date: 2025-12-27 14:09:02.491868

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '2355c6e79800'
down_revision: Union[str, None] = '45ca633d638a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('apps', sa.Column('apple_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.create_index(op.f('ix_apps_apple_id'), 'apps', ['apple_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_apps_apple_id'), table_name='apps')
    op.drop_column('apps', 'apple_id')
    # ### end Alembic commands ###
