"""Merge AppGroup and OfferGroup into single Group table

Revision ID: 251443eb8f5e
Revises: 98ecb5d12e77
Create Date: 2025-12-27 14:57:34.589460

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '251443eb8f5e'
down_revision: Union[str, None] = '98ecb5d12e77'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # 1. Create new groups table
    op.create_table('groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('type', sa.String(length=10), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_groups_name'), 'groups', ['name'], unique=False)
    op.create_index(op.f('ix_groups_type'), 'groups', ['type'], unique=False)

    # 2. Update apps table - add new column, drop old FK, add new FK, drop old column
    op.add_column('apps', sa.Column('group_id', sa.Integer(), nullable=True))
    op.drop_constraint('apps_app_group_id_fkey', 'apps', type_='foreignkey')
    op.drop_index(op.f('ix_apps_app_group_id'), table_name='apps')
    op.drop_column('apps', 'app_group_id')
    op.create_index(op.f('ix_apps_group_id'), 'apps', ['group_id'], unique=False)
    op.create_foreign_key(None, 'apps', 'groups', ['group_id'], ['id'])

    # 3. Update offers table - add new column, drop old FK, add new FK, drop old column
    op.add_column('offers', sa.Column('group_id', sa.Integer(), nullable=True))
    op.drop_constraint('offers_offer_group_id_fkey', 'offers', type_='foreignkey')
    op.drop_index(op.f('ix_offers_offer_group_id'), table_name='offers')
    op.drop_column('offers', 'offer_group_id')
    op.create_index(op.f('ix_offers_group_id'), 'offers', ['group_id'], unique=False)
    op.create_foreign_key(None, 'offers', 'groups', ['group_id'], ['id'])

    # 4. Drop old tables (now safe - no FKs referencing them)
    op.drop_index(op.f('ix_app_groups_name'), table_name='app_groups')
    op.drop_table('app_groups')
    op.drop_index(op.f('ix_offer_groups_name'), table_name='offer_groups')
    op.drop_table('offer_groups')


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('offers', sa.Column('offer_group_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'offers', type_='foreignkey')
    op.create_foreign_key(op.f('offers_offer_group_id_fkey'), 'offers', 'offer_groups', ['offer_group_id'], ['id'])
    op.drop_index(op.f('ix_offers_group_id'), table_name='offers')
    op.create_index(op.f('ix_offers_offer_group_id'), 'offers', ['offer_group_id'], unique=False)
    op.drop_column('offers', 'group_id')
    op.add_column('apps', sa.Column('app_group_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'apps', type_='foreignkey')
    op.create_foreign_key(op.f('apps_app_group_id_fkey'), 'apps', 'app_groups', ['app_group_id'], ['id'])
    op.drop_index(op.f('ix_apps_group_id'), table_name='apps')
    op.create_index(op.f('ix_apps_app_group_id'), 'apps', ['app_group_id'], unique=False)
    op.drop_column('apps', 'group_id')
    op.create_table('offer_groups',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('offer_groups_pkey'))
    )
    op.create_index(op.f('ix_offer_groups_name'), 'offer_groups', ['name'], unique=True)
    op.create_table('app_groups',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('app_groups_pkey'))
    )
    op.create_index(op.f('ix_app_groups_name'), 'app_groups', ['name'], unique=True)
    op.drop_index(op.f('ix_groups_type'), table_name='groups')
    op.drop_index(op.f('ix_groups_name'), table_name='groups')
    op.drop_table('groups')
    # ### end Alembic commands ###
