"""Add offer_geos table, remove geo_id from offers

Revision ID: 45ca633d638a
Revises: b3762d726525
Create Date: 2025-12-27 13:50:36.687383

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '45ca633d638a'
down_revision: Union[str, None] = 'b3762d726525'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('offer_geos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('offer_id', sa.Integer(), nullable=False),
    sa.Column('geo_id', sa.Integer(), nullable=False),
    sa.Column('app_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['app_id'], ['apps.id'], ),
    sa.ForeignKeyConstraint(['geo_id'], ['geos.id'], ),
    sa.ForeignKeyConstraint(['offer_id'], ['offers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('app_id', 'geo_id', name='uq_offer_geos_app_geo')
    )
    op.create_index(op.f('ix_offer_geos_app_id'), 'offer_geos', ['app_id'], unique=False)
    op.create_index(op.f('ix_offer_geos_geo_id'), 'offer_geos', ['geo_id'], unique=False)
    op.create_index(op.f('ix_offer_geos_offer_id'), 'offer_geos', ['offer_id'], unique=False)
    op.drop_index(op.f('ix_offers_geo_id'), table_name='offers')
    op.drop_constraint(op.f('offers_geo_id_fkey'), 'offers', type_='foreignkey')
    op.drop_column('offers', 'geo_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('offers', sa.Column('geo_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('offers_geo_id_fkey'), 'offers', 'geos', ['geo_id'], ['id'])
    op.create_index(op.f('ix_offers_geo_id'), 'offers', ['geo_id'], unique=False)
    op.drop_index(op.f('ix_offer_geos_offer_id'), table_name='offer_geos')
    op.drop_index(op.f('ix_offer_geos_geo_id'), table_name='offer_geos')
    op.drop_index(op.f('ix_offer_geos_app_id'), table_name='offer_geos')
    op.drop_table('offer_geos')
    # ### end Alembic commands ###
