"""add geo_source to init_logs

Revision ID: 5cb5a1f8c283
Revises: 74e4a7af2157
Create Date: 2026-03-16 16:08:21.571369

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "5cb5a1f8c283"
down_revision: Union[str, None] = "74e4a7af2157"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "init_logs",
        sa.Column(
            "geo_source", sqlmodel.sql.sqltypes.AutoString(length=15), nullable=True
        ),
    )
    op.create_unique_constraint("uq_link_app_geo", "links", ["app_id", "geo_id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_link_app_geo", "links", type_="unique")
    op.drop_column("init_logs", "geo_source")
    # ### end Alembic commands ###
