"""add sdk fields: api_key, icon_name, link filters, push_enabled

Revision ID: 69856230db0b
Revises: rename_aog_links
Create Date: 2026-03-15 21:24:37.189724

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '69856230db0b'
down_revision: Union[str, None] = 'rename_aog_links'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('apps', sa.Column('api_key', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('apps', sa.Column('icon_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.create_index(op.f('ix_apps_api_key'), 'apps', ['api_key'], unique=False)
    op.add_column('clients', sa.Column('push_enabled', sa.Boolean(), nullable=False))
    op.add_column('links', sa.Column('language', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('links', sa.Column('min_version', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('links', sa.Column('max_version', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('links', sa.Column('att_status', sa.String(length=20), nullable=True))
    op.add_column('links', sa.Column('rate_delay_sec', sa.Integer(), nullable=True))
    op.add_column('links', sa.Column('push_delay_sec', sa.Integer(), nullable=True))
    op.add_column('links', sa.Column('icon_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.drop_constraint(op.f('uq_link_app_geo'), 'links', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_link_app_geo'), 'links', ['app_id', 'geo_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('links', 'icon_name')
    op.drop_column('links', 'push_delay_sec')
    op.drop_column('links', 'rate_delay_sec')
    op.drop_column('links', 'att_status')
    op.drop_column('links', 'max_version')
    op.drop_column('links', 'min_version')
    op.drop_column('links', 'language')
    op.drop_column('clients', 'push_enabled')
    op.drop_index(op.f('ix_apps_api_key'), table_name='apps')
    op.drop_column('apps', 'icon_name')
    op.drop_column('apps', 'api_key')
    # ### end Alembic commands ###
