"""Add AppGroup OfferGroup and AppOfferGeo tables

Revision ID: 98ecb5d12e77
Revises: 2355c6e79800
Create Date: 2025-12-27 14:53:09.655282

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '98ecb5d12e77'
down_revision: Union[str, None] = '2355c6e79800'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_app_groups_name'), 'app_groups', ['name'], unique=True)
    op.create_table('offer_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_offer_groups_name'), 'offer_groups', ['name'], unique=True)
    op.create_table('app_offer_geo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('app_id', sa.Integer(), nullable=False),
    sa.Column('offer_id', sa.Integer(), nullable=False),
    sa.Column('geo_id', sa.Integer(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('weight', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['app_id'], ['apps.id'], ),
    sa.ForeignKeyConstraint(['geo_id'], ['geos.id'], ),
    sa.ForeignKeyConstraint(['offer_id'], ['offers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('app_id', 'geo_id', name='uq_app_offer_geo_app_geo')
    )
    op.create_index(op.f('ix_app_offer_geo_app_id'), 'app_offer_geo', ['app_id'], unique=False)
    op.create_index(op.f('ix_app_offer_geo_geo_id'), 'app_offer_geo', ['geo_id'], unique=False)
    op.create_index(op.f('ix_app_offer_geo_is_active'), 'app_offer_geo', ['is_active'], unique=False)
    op.create_index(op.f('ix_app_offer_geo_offer_id'), 'app_offer_geo', ['offer_id'], unique=False)
    op.drop_index(op.f('ix_offer_geos_app_id'), table_name='offer_geos')
    op.drop_index(op.f('ix_offer_geos_geo_id'), table_name='offer_geos')
    op.drop_index(op.f('ix_offer_geos_offer_id'), table_name='offer_geos')
    op.drop_table('offer_geos')
    op.add_column('apps', sa.Column('app_group_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_apps_app_group_id'), 'apps', ['app_group_id'], unique=False)
    op.create_foreign_key(None, 'apps', 'app_groups', ['app_group_id'], ['id'])
    op.add_column('offers', sa.Column('offer_group_id', sa.Integer(), nullable=True))
    op.drop_index(op.f('ix_offers_app_id'), table_name='offers')
    op.create_index(op.f('ix_offers_offer_group_id'), 'offers', ['offer_group_id'], unique=False)
    op.drop_constraint(op.f('offers_app_id_fkey'), 'offers', type_='foreignkey')
    op.create_foreign_key(None, 'offers', 'offer_groups', ['offer_group_id'], ['id'])
    op.drop_column('offers', 'app_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('offers', sa.Column('app_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'offers', type_='foreignkey')
    op.create_foreign_key(op.f('offers_app_id_fkey'), 'offers', 'apps', ['app_id'], ['id'])
    op.drop_index(op.f('ix_offers_offer_group_id'), table_name='offers')
    op.create_index(op.f('ix_offers_app_id'), 'offers', ['app_id'], unique=False)
    op.drop_column('offers', 'offer_group_id')
    op.drop_constraint(None, 'apps', type_='foreignkey')
    op.drop_index(op.f('ix_apps_app_group_id'), table_name='apps')
    op.drop_column('apps', 'app_group_id')
    op.create_table('offer_geos',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('offer_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('geo_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('app_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['app_id'], ['apps.id'], name=op.f('offer_geos_app_id_fkey')),
    sa.ForeignKeyConstraint(['geo_id'], ['geos.id'], name=op.f('offer_geos_geo_id_fkey')),
    sa.ForeignKeyConstraint(['offer_id'], ['offers.id'], name=op.f('offer_geos_offer_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('offer_geos_pkey')),
    sa.UniqueConstraint('app_id', 'geo_id', name=op.f('uq_offer_geos_app_geo'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_offer_geos_offer_id'), 'offer_geos', ['offer_id'], unique=False)
    op.create_index(op.f('ix_offer_geos_geo_id'), 'offer_geos', ['geo_id'], unique=False)
    op.create_index(op.f('ix_offer_geos_app_id'), 'offer_geos', ['app_id'], unique=False)
    op.drop_index(op.f('ix_app_offer_geo_offer_id'), table_name='app_offer_geo')
    op.drop_index(op.f('ix_app_offer_geo_is_active'), table_name='app_offer_geo')
    op.drop_index(op.f('ix_app_offer_geo_geo_id'), table_name='app_offer_geo')
    op.drop_index(op.f('ix_app_offer_geo_app_id'), table_name='app_offer_geo')
    op.drop_table('app_offer_geo')
    op.drop_index(op.f('ix_offer_groups_name'), table_name='offer_groups')
    op.drop_table('offer_groups')
    op.drop_index(op.f('ix_app_groups_name'), table_name='app_groups')
    op.drop_table('app_groups')
    # ### end Alembic commands ###
