"""add_geo_and_offer_tables

Revision ID: b3762d726525
Revises: 001_initial
Create Date: 2025-12-25 00:03:00.630867

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b3762d726525'
down_revision: Union[str, None] = '001_initial'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('geos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_geos_code'), 'geos', ['code'], unique=True)
    op.create_index(op.f('ix_geos_is_default'), 'geos', ['is_default'], unique=False)
    op.create_table('offers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('app_id', sa.Integer(), nullable=False),
    sa.Column('geo_id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('weight', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['app_id'], ['apps.id'], ),
    sa.ForeignKeyConstraint(['geo_id'], ['geos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_offers_app_id'), 'offers', ['app_id'], unique=False)
    op.create_index(op.f('ix_offers_geo_id'), 'offers', ['geo_id'], unique=False)
    op.create_index(op.f('ix_offers_is_active'), 'offers', ['is_active'], unique=False)
    op.create_index(op.f('ix_offers_priority'), 'offers', ['priority'], unique=False)
    op.drop_column('apps', 'casino_url')
    op.alter_column('init_logs', 'request_headers',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('init_logs', 'request_body',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('init_logs', 'response_body',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('init_logs', 'response_body',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('init_logs', 'request_body',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('init_logs', 'request_headers',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    op.add_column('apps', sa.Column('casino_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_offers_priority'), table_name='offers')
    op.drop_index(op.f('ix_offers_is_active'), table_name='offers')
    op.drop_index(op.f('ix_offers_geo_id'), table_name='offers')
    op.drop_index(op.f('ix_offers_app_id'), table_name='offers')
    op.drop_table('offers')
    op.drop_index(op.f('ix_geos_is_default'), table_name='geos')
    op.drop_index(op.f('ix_geos_code'), table_name='geos')
    op.drop_table('geos')
    # ### end Alembic commands ###
