"""add geo_id to init_logs

Revision ID: bb49e8f063a9
Revises: 5cb5a1f8c283
Create Date: 2026-03-16 17:28:11.511045

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "bb49e8f063a9"
down_revision: Union[str, None] = "5cb5a1f8c283"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("init_logs", sa.Column("geo_id", sa.Integer(), nullable=True))
    op.create_index(op.f("ix_init_logs_geo_id"), "init_logs", ["geo_id"], unique=False)
    op.create_foreign_key(None, "init_logs", "geos", ["geo_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "init_logs", type_="foreignkey")
    op.drop_index(op.f("ix_init_logs_geo_id"), table_name="init_logs")
    op.drop_column("init_logs", "geo_id")
    # ### end Alembic commands ###
